export const FETCH_ORDER = 'FETCH_ORDER';
export const FETCH_ALL_ORDERS = 'FETCH_ALL_ORDERS';
export const EDIT_ORDER = 'EDIT_ORDER';
export const EDIT_ORDER_SUCCESS = 'EDIT_ORDER_SUCCESS';
export const EDIT_ORDER_FAILURE = 'EDIT_ORDER_FAILURE';
